project:
  type: website

website:
  title: "{{cookiecutter.project_name}}"
  page-navigation: true
  navbar:
    left:
      - text: "Getting started"
        file: getting_started/index.qmd
      - text: "User guide"
        file: user_guide/index.qmd
      - text: "Contributing"
        file: contributing/index.qmd
    right:
      - icon: github
        href: {{ cookiecutter.project_url }}
        aria-label: GitHub

  sidebar:
    - title: "Getting started"
      contents:
        - getting_started/index.qmd
        - getting_started/installation.qmd
    - title: "User guide"
      contents:
        - user_guide/index.qmd
        - user_guide/{{cookiecutter.model_shortname}}.qmd
    - title: "Contributing"
      contents:
        - contributing/index.qmd

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true

bibliography: references.bib
number-sections: true

quartodoc:
  style: pkgdown
  dir: python/reference
  title: API Reference
  package: {{cookiecutter.project_slug}}
  sections:
    - title: Model
      desc: The Model class represents an entire {{ cookiecutter.project_name }} model.
      contents:
        - Model
