---
name: Tests development

on:
  schedule:
    - cron: 0 0 * * * # run on main everyday at 00:00
  push:
    branches: [main]
    paths:
      - tests/*
      - {{cookiecutter.project_slug}}/*
  pull_request:
    branches: [main]
    paths:
      - tests/*
      - {{cookiecutter.project_slug}}/*

Jobs:
  Test-Dev:
    name: {{' ${{ matrix.os }} - py${{ matrix.python-version }} '}}
    runs-on: {{'${{ matrix.os }} '}}
    timeout-minutes: 10
    defaults:
      run:
        shell: bash -l {0}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
      - run: pip install tomli
      - run: python make_env.py test
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: {{'${{ matrix.python-version }} '}}
          miniforge-variant: Mambaforge
          channels: conda-forge, defaults
          channel-priority: strict
          environment-file: environment.yml
          activate-environment: {{cookiecutter.project_slug}}

      - name: Install HydroMT-core dev
        run: |
          python -m pip install git+https://github.com/Deltares/hydromt.git@main --user

      - name: Test
        run: python -m pytest --verbose --cov={{cookiecutter.project_slug}} --cov-report xml

      - uses: codecov/codecov-action@v3

concurrency:
  group: {{' ${{ github.workflow }}-${{ github.ref }} '}}
  cancel-in-progress: true